/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package observerpattern.view;

import java.awt.Graphics;
import javax.swing.DefaultComboBoxModel;
import observerpattern.model.stats.framework.DSStatFactory;
import observerpattern.model.stats.derived.DSEquipmentManager;

/**
 *
 * @author KeithW
 */
public class DSEquipmentPickerView extends javax.swing.JPanel {

    private DefaultComboBoxModel<String> modelArmor, modelShields, modelMeleeWeapons, modelRangedWeapons;
    private DSStatFactory armorStats, shieldStats, weaponMeleeStats, weaponRangedStats;
    private DSEquipmentManager equipment;

    /**
     * Creates new form DSEquipmentPickerView
     */
    public DSEquipmentPickerView() {
        initComponents();

        modelArmor = new DefaultComboBoxModel();
        modelShields = new DefaultComboBoxModel();
        modelMeleeWeapons = new DefaultComboBoxModel();
        modelRangedWeapons = new DefaultComboBoxModel();

        this.jComboArmor.setModel(modelArmor);
        this.jComboShield.setModel(modelShields);
        this.jComboMeleeWeapon.setModel(modelMeleeWeapons);
        this.jComboRangedWeapon.setModel(modelRangedWeapons);

        load();

    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);

        boolean enabled = this.equipment != null;
        
        this.jComboArmor.setEnabled(enabled);
        this.jComboMeleeWeapon.setEnabled(enabled);
        this.jComboRangedWeapon.setEnabled(enabled);
        this.jComboShield.setEnabled(enabled);

    }

    public void setModel(DSEquipmentManager equipment) {
        this.equipment = equipment;

        this.jComboMeleeWeapon.setSelectedIndex(0);

        repaint();

    }

    // Load the reference data and populate the combo boxes
    private void load() {

        // Load in the reference data for armor, shields and weapons
        armorStats = new DSStatFactory("armor_stats");
        armorStats.load();

        shieldStats = new DSStatFactory("shield_stats");
        shieldStats.load();

        weaponMeleeStats = new DSStatFactory("melee_weapon_stats");
        weaponMeleeStats.load();

        weaponRangedStats = new DSStatFactory("ranged_weapon_stats");
        weaponRangedStats.load();

        // Populate the combo box models with the names
        for (String key : armorStats.getGroups()) {
            modelArmor.addElement(key);
        }

        for (String key : shieldStats.getGroups()) {
            modelShields.addElement(key);
        }

        for (String key : weaponMeleeStats.getGroups()) {
            modelMeleeWeapons.addElement(key);
        }

        for (String key : weaponRangedStats.getGroups()) {
            modelRangedWeapons.addElement(key);
        }

    }

    public String getArmor() {

        return (String) modelArmor.getSelectedItem();
    }

    public String getShield() {

        return (String) modelShields.getSelectedItem();
    }

    public String getMeleeWeapon() {

        String sWeaponName = (String) modelMeleeWeapons.getSelectedItem();

        return sWeaponName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboArmor = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboShield = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboMeleeWeapon = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboRangedWeapon = new javax.swing.JComboBox();

        jLabel1.setText("Armor");

        jComboArmor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboArmor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboArmorItemStateChanged(evt);
            }
        });

        jLabel2.setText("Shield");

        jComboShield.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboShield.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboShieldItemStateChanged(evt);
            }
        });

        jLabel3.setText("Melee Weapon");

        jComboMeleeWeapon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboMeleeWeapon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboMeleeWeaponItemStateChanged(evt);
            }
        });

        jLabel4.setText("Ranged Weapon");

        jComboRangedWeapon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboRangedWeapon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboRangedWeaponItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboArmor, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboShield, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboMeleeWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboRangedWeapon, 0, 179, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jComboArmor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2)
                .addComponent(jComboShield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3)
                .addComponent(jComboMeleeWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel4)
                .addComponent(jComboRangedWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboMeleeWeaponItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboMeleeWeaponItemStateChanged
        // TODO add your handling code here:

        if (this.equipment != null) {
            String sWeaponName = (String) modelMeleeWeapons.getSelectedItem();
            this.equipment.equipMeleeWeapon(sWeaponName);
        }

    }//GEN-LAST:event_jComboMeleeWeaponItemStateChanged

    private void jComboShieldItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboShieldItemStateChanged
        // TODO add your handling code here:
        if (this.equipment != null) {
            String sItemName = (String) modelShields.getSelectedItem();
            this.equipment.equipShield(sItemName);
        }

    }//GEN-LAST:event_jComboShieldItemStateChanged

    private void jComboArmorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboArmorItemStateChanged
        // TODO add your handling code here:
        if (this.equipment != null) {
            String sItemName = (String) modelArmor.getSelectedItem();
            this.equipment.equipArmor(sItemName);
        }

    }//GEN-LAST:event_jComboArmorItemStateChanged

    private void jComboRangedWeaponItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboRangedWeaponItemStateChanged
        // TODO add your handling code here:
        if (this.equipment != null) {
            String sWeaponName = (String) modelRangedWeapons.getSelectedItem();
            this.equipment.equipRangedWeapon(sWeaponName);
        }

    }//GEN-LAST:event_jComboRangedWeaponItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboArmor;
    private javax.swing.JComboBox jComboMeleeWeapon;
    private javax.swing.JComboBox jComboRangedWeapon;
    private javax.swing.JComboBox jComboShield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
